import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import fs from "fs";
import path from "path";

// Returns an autogenerated sidebar item only when the directory exists.
// This makes the sidebar resilient to schemas that lack certain type categories
// (e.g. no interfaces or inputs in a simple domain model).
function autoDir(dirName: string) {
  const abs = path.join(__dirname, "docs", dirName);
  return fs.existsSync(abs) ? [{ type: "autogenerated" as const, dirName }] : [];
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "elements/schema",
    {
      type: "category",
      label: "Types",
      items: [
        {
          type: "category",
          label: "Field Containers",
          items: [
            { type: "category", label: "Objects", items: autoDir("elements/types/objects") },
            { type: "category", label: "Interfaces", items: autoDir("elements/types/interfaces") },
            { type: "category", label: "Inputs", items: autoDir("elements/types/inputs") },
          ].filter((c) => c.items.length > 0),
        },
        { type: "category", label: "Enums", items: autoDir("elements/types/enums") },
        { type: "category", label: "Scalars", items: autoDir("elements/types/scalars") },
        { type: "category", label: "Queries", items: autoDir("elements/operations/queries") },
      ].filter((c) => "items" in c && (c.items as unknown[]).length > 0),
    },
    {
      type: "category",
      label: "Other",
      items: [
        { type: "category", label: "Directives", items: autoDir("elements/types/directives") },
      ].filter((c) => c.items.length > 0),
    },
  ],
};

export default sidebars;
